// supabase/seed-data.ts — Tareas 2.1 y 2.2 de TAREAS.md
//
// Los 22 proyectos y las 82 tareas del Excel del reto (hojas `Projects` y
// `Tasks`), ya transformados al esquema de la Tarea 1.1. La transcripción se
// hizo con un script de preparación (paso 2.1.a, no queda en el repo); de acá en
// adelante este archivo es la fuente de verdad y se edita a mano.
//
// Qué se transformó, y por qué:
//   · 2.1.e  Tildes. El Excel viene sin acentos y los CHECK de 001_tables.sql
//            exigen la grafía correcta ('Ejecucion' es rechazado). Alcanza a los
//            enumerados y a los `summary`, que son texto visible en la UI.
//   · 2.1.f  Tipos. El Excel entrega todo como texto: `is_overdue` venía
//            'Si'/'No' (34/48) y los montos como cadenas.
//   · 2.1.g  `title` sin el sufijo ' - {project_name}'. El nombre del proyecto ya
//            vive en `projects.project_name`; repetirlo en cada tarjeta del
//            Kanban es ruido. Además es lo que hace resoluble la Tarea 2.2.
//   · 2.1.h  `open_tasks` y `overdue_tasks` NO se siembran: son derivadas y las
//            mantiene el trigger de 002_triggers_score.sql. El Excel además las
//            trae desactualizadas en 6 de 22 proyectos.
//   · 2.1.i  Columnas descartadas: `last_progress` (duplicado exacto de `detail`
//            en las 82 filas), `recent_completed_examples` (apunta a códigos que
//            no existen en la hoja `Tasks`) y `engagement_type`/`client_alias`/
//            `project_name` de la hoja `Tasks` (denormalizadas, salen por join).
//   · 2.1.j  `next_step` queda null en los 22 a propósito: proponerlo es trabajo
//            del usuario (Tarea 6.3). Los 13 proyectos 'Bloqueado' arrancan
//            mostrando ⚠️, que es justo lo que el sistema tiene que evidenciar.
//   · 2.1.k  `blocker_reason` se llena en los 17 proyectos que traen texto en
//            `blockers`, no solo en los 13 con health='Bloqueado'.
//
// `blocked_since` y `blocker_owner` quedan null: el Excel no los trae y se
// completan desde la UI (Tarea 6.3). El texto de `blocker_reason` y de `detail`
// está en inglés porque así viene el dataset; no se traduce, no es alcance de
// esta tarea.

import { convertirAUSD } from '@/lib/currency';
import type { Project, Task } from '@/lib/types';

/**
 * Un proyecto tal como se inserta: el `Project` completo menos las tres columnas
 * derivadas, que las calculan los triggers de la Tarea 1.2 (2.1.h).
 */
export type SeedProject = Omit<Project, 'open_tasks' | 'overdue_tasks' | 'score_proyecto'>;

/** Lo que se escribe abajo a mano: sin `business_value_usd`, que se calcula. */
type ProyectoBase = Omit<SeedProject, 'business_value_usd'>;

/**
 * Una tarea del seed. Arrastra `dependency` —el texto crudo de la columna del
 * Excel— porque es la entrada de `resolverDependencias` (Tarea 2.2), que es
 * quien llena `depends_on_task_code`. Hasta entonces las 82 nacen en null.
 */
export type SeedTask = Task & { dependency: string | null };

const proyectosBase: ProyectoBase[] = [
  {
    project_code: 'PRJ-01',
    engagement_type: 'Proyecto',
    client_alias: 'Atlas Foods',
    project_name: 'Global Contract Management',
    project_type_api: 'Automatización',
    stage: 'Ejecución',
    status: 'Activo',
    health: 'Bloqueado',
    owner_alias: 'Daniel Rojas',
    owner_role: 'Commercial / Delivery',
    start_date: null,
    target_date: null,
    business_value: 28000,
    currency: 'USD',
    next_step: null,
    blocker_reason: 'There are external dependencies or pending accesses. There are overdue tasks without a clear close path.',
    blocked_since: null,
    blocker_owner: null,
    summary: 'Plataforma Integral de Gestión de Contratos para el Equipo Legal Global.',
  },
  {
    project_code: 'PRJ-02',
    engagement_type: 'Mantenimiento o recurrente',
    client_alias: 'Astera Ops',
    project_name: 'Observability Hub',
    project_type_api: 'Consultoría',
    stage: 'Ejecución',
    status: 'Activo',
    health: 'Bloqueado',
    owner_alias: 'Daniel Rojas',
    owner_role: 'Commercial / Delivery',
    start_date: null,
    target_date: null,
    business_value: 8000,
    currency: 'USD',
    next_step: null,
    blocker_reason: 'There are external dependencies or pending accesses. There are overdue tasks without a clear close path. This service requires ongoing follow-up and periodic cleanup.',
    blocked_since: null,
    blocker_owner: null,
    summary: 'Sistema de observabilidad multi-cliente (salud + adopción).',
  },
  {
    project_code: 'PRJ-03',
    engagement_type: 'Mantenimiento o recurrente',
    client_alias: 'Lunara Health',
    project_name: 'Patient Care Assistant',
    project_type_api: 'Automatización',
    stage: 'Ejecución',
    status: 'Activo',
    health: 'Bloqueado',
    owner_alias: 'Camila Torres',
    owner_role: 'Delivery',
    start_date: '2026-03-02',
    target_date: '2026-03-02',
    business_value: 14000,
    currency: 'USD',
    next_step: null,
    blocker_reason: 'There are external dependencies or pending accesses. There are overdue tasks without a clear close path. This service requires ongoing follow-up and periodic cleanup.',
    blocked_since: null,
    blocker_owner: null,
    summary: 'Sistema de reservas y chatbot.',
  },
  {
    project_code: 'PRJ-04',
    engagement_type: 'Proyecto',
    client_alias: 'Pioneer Insurance',
    project_name: 'Quotation Engine',
    project_type_api: 'Automatización',
    stage: 'Ejecución',
    status: 'Activo',
    health: 'Bloqueado',
    owner_alias: 'Camila Torres',
    owner_role: 'Delivery',
    start_date: '2026-03-02',
    target_date: '2026-03-05',
    business_value: 25000,
    currency: 'USD',
    next_step: null,
    blocker_reason: 'There are external dependencies or pending accesses. There are overdue tasks without a clear close path.',
    blocked_since: null,
    blocker_owner: null,
    summary: 'Automatización de slips de cotización.',
  },
  {
    project_code: 'PRJ-05',
    engagement_type: 'Mantenimiento o recurrente',
    client_alias: 'Orion Mobility',
    project_name: 'Multi-Brand Sales Assistant',
    project_type_api: 'Automatización',
    stage: 'Ejecución',
    status: 'Activo',
    health: 'Bloqueado',
    owner_alias: 'Laura Gomez',
    owner_role: 'Delivery',
    start_date: '2026-02-25',
    target_date: '2026-03-16',
    business_value: 3000,
    currency: 'USD',
    next_step: null,
    blocker_reason: 'There are external dependencies or pending accesses. There are overdue tasks without a clear close path. This service requires ongoing follow-up and periodic cleanup.',
    blocked_since: null,
    blocker_owner: null,
    summary: 'Proyecto creado vía API.',
  },
  {
    project_code: 'PRJ-06',
    engagement_type: 'Mantenimiento o recurrente',
    client_alias: 'Nova Recovery',
    project_name: 'Recovery and Compensation Ops',
    project_type_api: 'Automatización',
    stage: 'Ejecución',
    status: 'Activo',
    health: 'Bloqueado',
    owner_alias: 'Laura Gomez',
    owner_role: 'Delivery',
    start_date: '2026-02-27',
    target_date: '2026-03-16',
    business_value: 30000,
    currency: 'USD',
    next_step: null,
    blocker_reason: 'There are external dependencies or pending accesses. There are overdue tasks without a clear close path. This service requires ongoing follow-up and periodic cleanup.',
    blocked_since: null,
    blocker_owner: null,
    summary: 'Proyecto creado vía API.',
  },
  {
    project_code: 'PRJ-07',
    engagement_type: 'Proyecto',
    client_alias: 'Velora Credit',
    project_name: 'Credit Assistant',
    project_type_api: 'Consultoría',
    stage: 'Ejecución',
    status: 'Activo',
    health: 'Bloqueado',
    owner_alias: 'Camila Torres',
    owner_role: 'Delivery',
    start_date: '2026-04-08',
    target_date: '2026-04-13',
    business_value: null,
    currency: 'USD',
    next_step: null,
    blocker_reason: 'There are external dependencies or pending accesses. There are overdue tasks without a clear close path.',
    blocked_since: null,
    blocker_owner: null,
    summary: 'Proyecto sincronizado desde la plataforma de desarrollo (SUE).',
  },
  {
    project_code: 'PRJ-08',
    engagement_type: 'Proyecto',
    client_alias: 'Vector Partners',
    project_name: 'Messaging Qualification Engine',
    project_type_api: 'Consultoría',
    stage: 'Ejecución',
    status: 'Activo',
    health: 'Bloqueado',
    owner_alias: 'Camila Torres',
    owner_role: 'Delivery',
    start_date: null,
    target_date: '2026-04-27',
    business_value: 35000,
    currency: 'USD',
    next_step: null,
    blocker_reason: 'There are external dependencies or pending accesses. There are overdue tasks without a clear close path.',
    blocked_since: null,
    blocker_owner: null,
    summary: 'Proyecto sincronizado desde la plataforma de desarrollo (QUI).',
  },
  {
    project_code: 'PRJ-09',
    engagement_type: 'Proyecto',
    client_alias: 'Ferroline Industrial',
    project_name: 'Industrial OCR Quoter',
    project_type_api: 'Consultoría',
    stage: 'Ejecución',
    status: 'Activo',
    health: 'Bloqueado',
    owner_alias: 'Camila Torres',
    owner_role: 'Delivery',
    start_date: null,
    target_date: '2026-05-13',
    business_value: 22000,
    currency: 'USD',
    next_step: null,
    blocker_reason: 'There are external dependencies or pending accesses. There are overdue tasks without a clear close path.',
    blocked_since: null,
    blocker_owner: null,
    summary: 'Proyecto sincronizado desde la plataforma de desarrollo (TMX).',
  },
  {
    project_code: 'PRJ-10',
    engagement_type: 'Proyecto',
    client_alias: 'Pulse Creative',
    project_name: 'Commercial Image Pipeline',
    project_type_api: 'Consultoría',
    stage: 'Ejecución',
    status: 'Activo',
    health: 'Bloqueado',
    owner_alias: 'Camila Torres',
    owner_role: 'Delivery',
    start_date: null,
    target_date: '2026-05-15',
    business_value: 18000,
    currency: 'USD',
    next_step: null,
    blocker_reason: 'There are external dependencies or pending accesses. There are overdue tasks without a clear close path.',
    blocked_since: null,
    blocker_owner: null,
    summary: 'Proyecto sincronizado desde la plataforma de desarrollo (NEQ).',
  },
  {
    project_code: 'PRJ-11',
    engagement_type: 'Proyecto',
    client_alias: 'Civica Regional',
    project_name: 'Public Service Desk',
    project_type_api: 'Consultoría',
    stage: 'Ejecución',
    status: 'Activo',
    health: 'Bloqueado',
    owner_alias: 'Laura Gomez',
    owner_role: 'Delivery',
    start_date: null,
    target_date: '2026-05-21',
    business_value: 15000,
    currency: 'USD',
    next_step: null,
    blocker_reason: 'There are external dependencies or pending accesses. There are overdue tasks without a clear close path.',
    blocked_since: null,
    blocker_owner: null,
    summary: 'Proyecto sincronizado desde la plataforma de desarrollo (GOB).',
  },
  {
    project_code: 'PRJ-12',
    engagement_type: 'Proyecto',
    client_alias: 'Northfield Proteins',
    project_name: 'Plant Operations Automation',
    project_type_api: 'Consultoría',
    stage: 'Ejecución',
    status: 'Activo',
    health: 'Bloqueado',
    owner_alias: 'Mateo Ruiz',
    owner_role: 'Delivery',
    start_date: null,
    target_date: '2026-05-22',
    business_value: 9000,
    currency: 'USD',
    next_step: null,
    blocker_reason: 'There are external dependencies or pending accesses. There are overdue tasks without a clear close path.',
    blocked_since: null,
    blocker_owner: null,
    summary: 'Proyecto sincronizado desde la plataforma de desarrollo (NTB).',
  },
  {
    project_code: 'PRJ-13',
    engagement_type: 'Diagnóstico',
    client_alias: 'HelioGrid Energy',
    project_name: 'Commercial Automation Discovery',
    project_type_api: 'Consultoría',
    stage: 'Descubrimiento',
    status: 'Activo',
    health: 'En riesgo',
    owner_alias: 'Santiago Vera',
    owner_role: 'Delivery',
    start_date: null,
    target_date: '2026-05-22',
    business_value: 12000,
    currency: 'USD',
    next_step: null,
    blocker_reason: 'There are external dependencies or pending accesses. There are overdue tasks without a clear close path.',
    blocked_since: null,
    blocker_owner: null,
    summary: 'Proyecto sincronizado desde la plataforma de desarrollo (SVT).',
  },
  {
    project_code: 'PRJ-14',
    engagement_type: 'Diagnóstico',
    client_alias: 'Orion Mobility',
    project_name: 'Vehicle Photography Platform',
    project_type_api: 'Automatización',
    stage: 'Descubrimiento',
    status: 'Activo',
    health: 'En riesgo',
    owner_alias: 'Mateo Ruiz',
    owner_role: 'Delivery',
    start_date: '2026-04-16',
    target_date: null,
    business_value: 2000,
    currency: 'USD',
    next_step: null,
    blocker_reason: 'There are external dependencies or pending accesses. There are overdue tasks without a clear close path.',
    blocked_since: null,
    blocker_owner: null,
    summary: 'Plataforma para que concesionarios tomen fotos y reciban fotos profesionales.',
  },
  {
    project_code: 'PRJ-15',
    engagement_type: 'Diagnóstico',
    client_alias: 'Orion Mobility',
    project_name: 'Legal Documents Assistant',
    project_type_api: 'Automatización',
    stage: 'Descubrimiento',
    status: 'Activo',
    health: 'En riesgo',
    owner_alias: 'Laura Gomez',
    owner_role: 'Delivery',
    start_date: '2026-04-16',
    target_date: null,
    business_value: 1000,
    currency: 'USD',
    next_step: null,
    blocker_reason: 'There are external dependencies or pending accesses. There are overdue tasks without a clear close path.',
    blocked_since: null,
    blocker_owner: null,
    summary: 'Proyecto creado vía API.',
  },
  {
    project_code: 'PRJ-16',
    engagement_type: 'Diagnóstico',
    client_alias: 'Orion Mobility',
    project_name: 'Lead Acquisition System',
    project_type_api: 'Automatización',
    stage: 'Descubrimiento',
    status: 'Activo',
    health: 'En riesgo',
    owner_alias: 'Mateo Ruiz',
    owner_role: 'Delivery',
    start_date: '2026-04-16',
    target_date: null,
    business_value: 1000,
    currency: 'USD',
    next_step: null,
    blocker_reason: 'There are overdue tasks without a clear close path.',
    blocked_since: null,
    blocker_owner: null,
    summary: 'Proyecto creado vía API.',
  },
  {
    project_code: 'PRJ-17',
    engagement_type: 'Mantenimiento o recurrente',
    client_alias: 'Astera Ops',
    project_name: 'Billing Reconciliation Bot',
    project_type_api: 'Automatización',
    stage: 'Ejecución',
    status: 'Activo',
    health: 'Sano',
    owner_alias: 'Daniel Rojas',
    owner_role: 'Commercial / Delivery',
    start_date: '02/03/2026',
    target_date: '2026-08-28',
    business_value: 11000,
    currency: 'USD',
    next_step: null,
    blocker_reason: null,
    blocked_since: null,
    blocker_owner: null,
    summary: 'Conciliación automática de facturación contra el ERP del cliente.',
  },
  {
    project_code: 'PRJ-18',
    engagement_type: 'Proyecto',
    client_alias: 'Andes Retail',
    project_name: 'Inventory Forecasting',
    project_type_api: 'Automatización',
    stage: 'Ejecución',
    status: 'Activo',
    health: 'Sano',
    owner_alias: 'Mateo Ruiz',
    owner_role: 'Delivery',
    start_date: '2026-05-04',
    target_date: '2026-09-12',
    business_value: 85000000,
    currency: 'COP',
    next_step: null,
    blocker_reason: null,
    blocked_since: null,
    blocker_owner: null,
    summary: 'Pronóstico de inventario por punto de venta con reposición sugerida.',
  },
  {
    project_code: 'PRJ-19',
    engagement_type: 'Proyecto',
    client_alias: 'Meridian Legal',
    project_name: 'Contract Clause Extractor',
    project_type_api: 'Consultoría',
    stage: 'Ejecución',
    status: 'Activo',
    health: 'Sano',
    owner_alias: 'Andrea Molina',
    owner_role: 'Delivery',
    start_date: '2026-06-01',
    target_date: '2026-09-30',
    business_value: 19000,
    currency: 'USD',
    next_step: null,
    blocker_reason: null,
    blocked_since: null,
    blocker_owner: null,
    summary: 'Extracción de cláusulas y obligaciones desde contratos en PDF.',
  },
  {
    project_code: 'PRJ-20',
    engagement_type: 'Mantenimiento o recurrente',
    client_alias: 'Nova Recovery',
    project_name: 'Claims Status Notifier',
    project_type_api: 'Automatización',
    stage: 'Ejecución',
    status: 'Activo',
    health: 'Sano',
    owner_alias: 'Laura Gomez',
    owner_role: 'Delivery',
    start_date: '2026-04-20',
    target_date: '2026-10-15',
    business_value: 120000000,
    currency: 'COP',
    next_step: null,
    blocker_reason: null,
    blocked_since: null,
    blocker_owner: null,
    summary: 'Notificación automática de estado de reclamaciones por WhatsApp.',
  },
  {
    project_code: 'PRJ-21',
    engagement_type: 'Proyecto',
    client_alias: 'Cobalt Logistics',
    project_name: 'Route Optimization Pilot',
    project_type_api: 'Consultoría',
    stage: 'Ejecución',
    status: 'Activo',
    health: 'Sano',
    owner_alias: 'Santiago Vera',
    owner_role: 'Delivery',
    start_date: '2025-11-10',
    target_date: '2026-02-10',
    business_value: 16000,
    currency: 'USD',
    next_step: null,
    blocker_reason: null,
    blocked_since: null,
    blocker_owner: null,
    summary: 'Piloto de optimización de rutas para flota regional.',
  },
  {
    project_code: 'PRJ-22',
    engagement_type: 'Proyecto',
    client_alias: 'Vector Partners',
    project_name: 'Messaging Qualification Engine (Fase 2)',
    project_type_api: 'Consultoría',
    stage: 'Ejecución',
    status: 'Activo',
    health: 'Bloqueado',
    owner_alias: 'Camila Torres',
    owner_role: 'Delivery',
    start_date: null,
    target_date: '2026-04-27',
    business_value: 38000,
    currency: 'USD',
    next_step: null,
    blocker_reason: 'There are external dependencies or pending accesses. There are overdue tasks without a clear close path.',
    blocked_since: null,
    blocker_owner: null,
    summary: 'Proyecto sincronizado desde la plataforma de desarrollo (QUI).',
  },
];

/**
 * 2.1.d — `business_value_usd` sale de `lib/currency.ts`, no de un número
 * escrito a mano: si la tasa cambia, cambia acá también.
 */
export const seedProjects: SeedProject[] = proyectosBase.map((p) => ({
  ...p,
  business_value_usd: convertirAUSD(p.business_value, p.currency),
}));

const tareasBase: SeedTask[] = [
  {
    task_code: 'PRJ-01-T01',
    project_code: 'PRJ-01',
    assignee_alias: 'Daniel Rojas',
    assignee_role: 'Commercial / Delivery',
    priority: 'Alta',
    status: 'En progreso',
    due_date: '2026-07-12',
    is_overdue: true,
    title: 'Plan next delivery iteration',
    detail: 'Next iteration is being scoped with deliverables and owners.',
    dependency: null,
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-01-T02',
    project_code: 'PRJ-01',
    assignee_alias: 'Daniel Rojas',
    assignee_role: 'Commercial / Delivery',
    priority: 'Crítica',
    status: 'Por hacer',
    due_date: '2026-07-10',
    is_overdue: true,
    title: 'Resolve priority issue in pilot or production',
    detail: 'There is a user-visible issue affecting trust or adoption.',
    dependency: 'Functional validation and release checklist',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-01-T03',
    project_code: 'PRJ-01',
    assignee_alias: 'Daniel Rojas',
    assignee_role: 'Commercial / Delivery',
    priority: 'Media',
    status: 'Bloqueada',
    due_date: '2026-07-14',
    is_overdue: false,
    title: 'Align external dependency with client or vendor',
    detail: 'Waiting on client response, credentials, external API or business definition.',
    dependency: 'Resolve priority issue in pilot or production',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-01-T04',
    project_code: 'PRJ-01',
    assignee_alias: 'Daniel Rojas',
    assignee_role: 'Commercial / Delivery',
    priority: 'Alta',
    status: 'En revisión',
    due_date: '2026-07-16',
    is_overdue: false,
    title: 'Functional validation and release checklist',
    detail: 'Core build exists, but edge cases still need validation before closing the front.',
    dependency: 'Plan next delivery iteration',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-02-T01',
    project_code: 'PRJ-02',
    assignee_alias: 'Daniel Rojas',
    assignee_role: 'Commercial / Delivery',
    priority: 'Media',
    status: 'En progreso',
    due_date: '2026-07-14',
    is_overdue: false,
    title: 'Weekly KPI and quality monitoring',
    detail: 'Weekly review of volume, response time and out-of-range events.',
    dependency: null,
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-02-T02',
    project_code: 'PRJ-02',
    assignee_alias: 'Daniel Rojas',
    assignee_role: 'Commercial / Delivery',
    priority: 'Alta',
    status: 'Por hacer',
    due_date: '2026-07-11',
    is_overdue: true,
    title: 'Adjust the rule or automation causing most friction',
    detail: 'One automation is creating manual errors or rework and needs tuning.',
    dependency: 'Weekly KPI and quality monitoring',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-02-T03',
    project_code: 'PRJ-02',
    assignee_alias: 'Daniel Rojas',
    assignee_role: 'Commercial / Delivery',
    priority: 'Baja',
    status: 'En revisión',
    due_date: '2026-07-18',
    is_overdue: false,
    title: 'Review historical backlog and clean stale tasks',
    detail: 'Old, duplicate or unclear tasks still need cleanup.',
    dependency: 'Weekly KPI and quality monitoring',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-02-T04',
    project_code: 'PRJ-02',
    assignee_alias: 'Daniel Rojas',
    assignee_role: 'Commercial / Delivery',
    priority: 'Alta',
    status: 'Bloqueada',
    due_date: '2026-07-09',
    is_overdue: true,
    title: 'Unblock recurrent service dependency',
    detail: 'A recurrent technical or operational dependency is hurting stability or improvements.',
    dependency: 'Adjust the rule or automation causing most friction',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-03-T01',
    project_code: 'PRJ-03',
    assignee_alias: 'Camila Torres',
    assignee_role: 'Delivery',
    priority: 'Media',
    status: 'En progreso',
    due_date: '2026-07-14',
    is_overdue: false,
    title: 'Weekly KPI and quality monitoring',
    detail: 'Weekly review of volume, response time and out-of-range events.',
    dependency: null,
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-03-T02',
    project_code: 'PRJ-03',
    assignee_alias: 'Camila Torres',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'Por hacer',
    due_date: '2026-07-11',
    is_overdue: true,
    title: 'Adjust the rule or automation causing most friction',
    detail: 'One automation is creating manual errors or rework and needs tuning.',
    dependency: 'Weekly KPI and quality monitoring',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-03-T03',
    project_code: 'PRJ-03',
    assignee_alias: 'Camila Torres',
    assignee_role: 'Delivery',
    priority: 'Baja',
    status: 'En revisión',
    due_date: '2026-07-18',
    is_overdue: false,
    title: 'Review historical backlog and clean stale tasks',
    detail: 'Old, duplicate or unclear tasks still need cleanup.',
    dependency: 'Weekly KPI and quality monitoring',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-03-T04',
    project_code: 'PRJ-03',
    assignee_alias: 'Camila Torres',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'Bloqueada',
    due_date: '2026-07-09',
    is_overdue: true,
    title: 'Unblock recurrent service dependency',
    detail: 'A recurrent technical or operational dependency is hurting stability or improvements.',
    dependency: 'Adjust the rule or automation causing most friction',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-04-T01',
    project_code: 'PRJ-04',
    assignee_alias: 'Camila Torres',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'En progreso',
    due_date: '2026-07-12',
    is_overdue: true,
    title: 'Plan next delivery iteration',
    detail: 'Next iteration is being scoped with deliverables and owners.',
    dependency: null,
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-04-T02',
    project_code: 'PRJ-04',
    assignee_alias: 'Camila Torres',
    assignee_role: 'Delivery',
    priority: 'Crítica',
    status: 'Por hacer',
    due_date: '2026-07-10',
    is_overdue: true,
    title: 'Resolve priority issue in pilot or production',
    detail: 'There is a user-visible issue affecting trust or adoption.',
    dependency: 'Align external dependency with client or vendor',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-04-T03',
    project_code: 'PRJ-04',
    assignee_alias: 'Camila Torres',
    assignee_role: 'Delivery',
    priority: 'Media',
    status: 'Bloqueada',
    due_date: '2026-07-14',
    is_overdue: false,
    title: 'Align external dependency with client or vendor',
    detail: 'Waiting on client response, credentials, external API or business definition.',
    dependency: 'Resolve priority issue in pilot or production',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-04-T04',
    project_code: 'PRJ-04',
    assignee_alias: 'Camila Torres',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'En revisión',
    due_date: '2026-07-16',
    is_overdue: false,
    title: 'Functional validation and release checklist',
    detail: 'Core build exists, but edge cases still need validation before closing the front.',
    dependency: 'Plan next delivery iteration',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-05-T01',
    project_code: 'PRJ-05',
    assignee_alias: 'Laura Gomez',
    assignee_role: 'Delivery',
    priority: 'Media',
    status: 'En progreso',
    due_date: '2026-07-14',
    is_overdue: false,
    title: 'Weekly KPI and quality monitoring',
    detail: 'Weekly review of volume, response time and out-of-range events.',
    dependency: null,
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-05-T02',
    project_code: 'PRJ-05',
    assignee_alias: 'Laura Gomez',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'Por hacer',
    due_date: '2026-07-11',
    is_overdue: true,
    title: 'Adjust the rule or automation causing most friction',
    detail: 'One automation is creating manual errors or rework and needs tuning.',
    dependency: 'Weekly KPI and quality monitoring',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-05-T03',
    project_code: 'PRJ-05',
    assignee_alias: 'Laura Gomez',
    assignee_role: 'Delivery',
    priority: 'Baja',
    status: 'En revisión',
    due_date: '2026-07-18',
    is_overdue: false,
    title: 'Review historical backlog and clean stale tasks',
    detail: 'Old, duplicate or unclear tasks still need cleanup.',
    dependency: 'Weekly KPI and quality monitoring',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-05-T04',
    project_code: 'PRJ-05',
    assignee_alias: 'Laura Gomez',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'Bloqueada',
    due_date: '2026-07-09',
    is_overdue: true,
    title: 'Unblock recurrent service dependency',
    detail: 'A recurrent technical or operational dependency is hurting stability or improvements.',
    dependency: 'Adjust the rule or automation causing most friction',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-06-T01',
    project_code: 'PRJ-06',
    assignee_alias: 'Laura Gomez',
    assignee_role: 'Delivery',
    priority: 'Media',
    status: 'En progreso',
    due_date: '2026-07-14',
    is_overdue: false,
    title: 'Weekly KPI and quality monitoring',
    detail: 'Weekly review of volume, response time and out-of-range events.',
    dependency: null,
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-06-T02',
    project_code: 'PRJ-06',
    assignee_alias: 'Laura Gomez',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'Por hacer',
    due_date: '2026-07-11',
    is_overdue: true,
    title: 'Adjust the rule or automation causing most friction',
    detail: 'One automation is creating manual errors or rework and needs tuning.',
    dependency: 'Weekly KPI and quality monitoring',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-06-T03',
    project_code: 'PRJ-06',
    assignee_alias: 'Laura Gomez',
    assignee_role: 'Delivery',
    priority: 'Baja',
    status: 'En revisión',
    due_date: '2026-07-18',
    is_overdue: false,
    title: 'Review historical backlog and clean stale tasks',
    detail: 'Old, duplicate or unclear tasks still need cleanup.',
    dependency: 'Weekly KPI and quality monitoring',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-06-T04',
    project_code: 'PRJ-06',
    assignee_alias: 'Laura Gomez',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'Bloqueada',
    due_date: '2026-07-09',
    is_overdue: true,
    title: 'Unblock recurrent service dependency',
    detail: 'A recurrent technical or operational dependency is hurting stability or improvements.',
    dependency: 'Adjust the rule or automation causing most friction',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-07-T01',
    project_code: 'PRJ-07',
    assignee_alias: 'Camila Torres',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'En progreso',
    due_date: '2026-07-12',
    is_overdue: true,
    title: 'Plan next delivery iteration',
    detail: 'Next iteration is being scoped with deliverables and owners.',
    dependency: null,
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-07-T02',
    project_code: 'PRJ-07',
    assignee_alias: 'Camila Torres',
    assignee_role: 'Delivery',
    priority: 'Crítica',
    status: 'Por hacer',
    due_date: '2026-07-10',
    is_overdue: true,
    title: 'Resolve priority issue in pilot or production',
    detail: 'There is a user-visible issue affecting trust or adoption.',
    dependency: 'Functional validation and release checklist',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-07-T03',
    project_code: 'PRJ-07',
    assignee_alias: 'Camila Torres',
    assignee_role: 'Delivery',
    priority: 'Media',
    status: 'Bloqueada',
    due_date: '2026-07-14',
    is_overdue: false,
    title: 'Align external dependency with client or vendor',
    detail: 'Waiting on client response, credentials, external API or business definition.',
    dependency: 'Resolve priority issue in pilot or production',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-07-T04',
    project_code: 'PRJ-07',
    assignee_alias: 'Camila Torres',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'En revisión',
    due_date: '2026-07-16',
    is_overdue: false,
    title: 'Functional validation and release checklist',
    detail: 'Core build exists, but edge cases still need validation before closing the front.',
    dependency: 'Plan next delivery iteration',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-08-T01',
    project_code: 'PRJ-08',
    assignee_alias: 'Camila Torres',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'En progreso',
    due_date: '2026-07-12',
    is_overdue: true,
    title: 'Plan next delivery iteration',
    detail: 'Next iteration is being scoped with deliverables and owners.',
    dependency: null,
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-08-T02',
    project_code: 'PRJ-08',
    assignee_alias: 'Camila Torres',
    assignee_role: 'Delivery',
    priority: 'Crítica',
    status: 'Por hacer',
    due_date: '2026-07-10',
    is_overdue: true,
    title: 'Resolve priority issue in pilot or production',
    detail: 'There is a user-visible issue affecting trust or adoption.',
    dependency: 'Functional validation and release checklist',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-08-T03',
    project_code: 'PRJ-08',
    assignee_alias: 'Camila Torres',
    assignee_role: 'Delivery',
    priority: 'Media',
    status: 'Bloqueada',
    due_date: '2026-07-14',
    is_overdue: false,
    title: 'Align external dependency with client or vendor',
    detail: 'Waiting on client response, credentials, external API or business definition.',
    dependency: 'Resolve priority issue in pilot or production',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-08-T04',
    project_code: 'PRJ-08',
    assignee_alias: 'Camila Torres',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'En revisión',
    due_date: '2026-07-16',
    is_overdue: false,
    title: 'Functional validation and release checklist',
    detail: 'Core build exists, but edge cases still need validation before closing the front.',
    dependency: 'Plan next delivery iteration',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-09-T01',
    project_code: 'PRJ-09',
    assignee_alias: 'Camila Torres',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'En progreso',
    due_date: '2026-07-12',
    is_overdue: true,
    title: 'Plan next delivery iteration',
    detail: 'Next iteration is being scoped with deliverables and owners.',
    dependency: null,
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-09-T02',
    project_code: 'PRJ-09',
    assignee_alias: 'Camila Torres',
    assignee_role: 'Delivery',
    priority: 'Crítica',
    status: 'Por hacer',
    due_date: '2026-07-10',
    is_overdue: true,
    title: 'Resolve priority issue in pilot or production',
    detail: 'There is a user-visible issue affecting trust or adoption.',
    dependency: 'Functional validation and release checklist',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-09-T03',
    project_code: 'PRJ-09',
    assignee_alias: 'Camila Torres',
    assignee_role: 'Delivery',
    priority: 'Media',
    status: 'Bloqueada',
    due_date: '2026-07-14',
    is_overdue: false,
    title: 'Align external dependency with client or vendor',
    detail: 'Waiting on client response, credentials, external API or business definition.',
    dependency: 'Resolve priority issue in pilot or production',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-09-T04',
    project_code: 'PRJ-09',
    assignee_alias: 'Camila Torres',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'En revisión',
    due_date: '2026-07-16',
    is_overdue: false,
    title: 'Functional validation and release checklist',
    detail: 'Core build exists, but edge cases still need validation before closing the front.',
    dependency: 'Plan next delivery iteration',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-10-T01',
    project_code: 'PRJ-10',
    assignee_alias: 'Camila Torres',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'En progreso',
    due_date: '2026-07-12',
    is_overdue: true,
    title: 'Plan next delivery iteration',
    detail: 'Next iteration is being scoped with deliverables and owners.',
    dependency: null,
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-10-T02',
    project_code: 'PRJ-10',
    assignee_alias: 'Camila Torres',
    assignee_role: 'Delivery',
    priority: 'Crítica',
    status: 'Por hacer',
    due_date: '2026-07-10',
    is_overdue: true,
    title: 'Resolve priority issue in pilot or production',
    detail: 'There is a user-visible issue affecting trust or adoption.',
    dependency: 'Functional validation and release checklist',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-10-T03',
    project_code: 'PRJ-10',
    assignee_alias: 'Camila Torres',
    assignee_role: 'Delivery',
    priority: 'Media',
    status: 'Bloqueada',
    due_date: '2026-07-14',
    is_overdue: false,
    title: 'Align external dependency with client or vendor',
    detail: 'Waiting on client response, credentials, external API or business definition.',
    dependency: 'Resolve priority issue in pilot or production',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-10-T04',
    project_code: 'PRJ-10',
    assignee_alias: 'Camila Torres',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'En revisión',
    due_date: '2026-07-16',
    is_overdue: false,
    title: 'Functional validation and release checklist',
    detail: 'Core build exists, but edge cases still need validation before closing the front.',
    dependency: 'Plan next delivery iteration',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-11-T01',
    project_code: 'PRJ-11',
    assignee_alias: 'Laura Gomez',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'En progreso',
    due_date: '2026-07-12',
    is_overdue: true,
    title: 'Plan next delivery iteration',
    detail: 'Next iteration is being scoped with deliverables and owners.',
    dependency: null,
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-11-T02',
    project_code: 'PRJ-11',
    assignee_alias: 'Laura Gomez',
    assignee_role: 'Delivery',
    priority: 'Crítica',
    status: 'Por hacer',
    due_date: '2026-07-10',
    is_overdue: true,
    title: 'Resolve priority issue in pilot or production',
    detail: 'There is a user-visible issue affecting trust or adoption.',
    dependency: 'Functional validation and release checklist',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-11-T03',
    project_code: 'PRJ-11',
    assignee_alias: 'Laura Gomez',
    assignee_role: 'Delivery',
    priority: 'Media',
    status: 'Bloqueada',
    due_date: '2026-07-14',
    is_overdue: false,
    title: 'Align external dependency with client or vendor',
    detail: 'Waiting on client response, credentials, external API or business definition.',
    dependency: 'Resolve priority issue in pilot or production',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-11-T04',
    project_code: 'PRJ-11',
    assignee_alias: 'Laura Gomez',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'En revisión',
    due_date: '2026-07-16',
    is_overdue: false,
    title: 'Functional validation and release checklist',
    detail: 'Core build exists, but edge cases still need validation before closing the front.',
    dependency: 'Plan next delivery iteration',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-12-T01',
    project_code: 'PRJ-12',
    assignee_alias: 'Mateo Ruiz',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'En progreso',
    due_date: '2026-07-12',
    is_overdue: true,
    title: 'Plan next delivery iteration',
    detail: 'Next iteration is being scoped with deliverables and owners.',
    dependency: null,
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-12-T02',
    project_code: 'PRJ-12',
    assignee_alias: 'Mateo Ruiz',
    assignee_role: 'Delivery',
    priority: 'Crítica',
    status: 'Por hacer',
    due_date: '2026-07-10',
    is_overdue: true,
    title: 'Resolve priority issue in pilot or production',
    detail: 'There is a user-visible issue affecting trust or adoption.',
    dependency: 'Functional validation and release checklist',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-12-T03',
    project_code: 'PRJ-12',
    assignee_alias: 'Mateo Ruiz',
    assignee_role: 'Delivery',
    priority: 'Media',
    status: 'Bloqueada',
    due_date: '2026-07-14',
    is_overdue: false,
    title: 'Align external dependency with client or vendor',
    detail: 'Waiting on client response, credentials, external API or business definition.',
    dependency: 'Resolve priority issue in pilot or production',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-12-T04',
    project_code: 'PRJ-12',
    assignee_alias: 'Mateo Ruiz',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'En revisión',
    due_date: '2026-07-16',
    is_overdue: false,
    title: 'Functional validation and release checklist',
    detail: 'Core build exists, but edge cases still need validation before closing the front.',
    dependency: 'Plan next delivery iteration',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-13-T01',
    project_code: 'PRJ-13',
    assignee_alias: 'Santiago Vera',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'En progreso',
    due_date: '2026-07-11',
    is_overdue: false,
    title: 'Stakeholder mapping and scope',
    detail: 'Interviews and dependency map are in progress.',
    dependency: null,
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-13-T02',
    project_code: 'PRJ-13',
    assignee_alias: 'Santiago Vera',
    assignee_role: 'Delivery',
    priority: 'Crítica',
    status: 'Por hacer',
    due_date: '2026-07-09',
    is_overdue: true,
    title: 'Audit current flow and breakpoints',
    detail: 'Current process timings, handoffs and failure points are still undocumented.',
    dependency: 'Stakeholder mapping and scope',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-13-T03',
    project_code: 'PRJ-13',
    assignee_alias: 'Santiago Vera',
    assignee_role: 'Delivery',
    priority: 'Media',
    status: 'En revisión',
    due_date: '2026-07-15',
    is_overdue: false,
    title: 'Define solution hypotheses and quick wins',
    detail: 'First set of quick wins is drafted and waiting for validation.',
    dependency: 'Audit current flow and breakpoints',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-13-T04',
    project_code: 'PRJ-13',
    assignee_alias: 'Santiago Vera',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'Bloqueada',
    due_date: '2026-07-08',
    is_overdue: true,
    title: 'Get access to key data sources',
    detail: 'Blocked by permissions, repository access or owner confirmation.',
    dependency: 'Stakeholder mapping and scope',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-14-T01',
    project_code: 'PRJ-14',
    assignee_alias: 'Mateo Ruiz',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'En progreso',
    due_date: '2026-07-11',
    is_overdue: false,
    title: 'Stakeholder mapping and scope',
    detail: 'Interviews and dependency map are in progress.',
    dependency: null,
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-14-T02',
    project_code: 'PRJ-14',
    assignee_alias: 'Mateo Ruiz',
    assignee_role: 'Delivery',
    priority: 'Crítica',
    status: 'Por hacer',
    due_date: '2026-07-09',
    is_overdue: true,
    title: 'Audit current flow and breakpoints',
    detail: 'Current process timings, handoffs and failure points are still undocumented.',
    dependency: 'Stakeholder mapping and scope',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-14-T03',
    project_code: 'PRJ-14',
    assignee_alias: 'Mateo Ruiz',
    assignee_role: 'Delivery',
    priority: 'Media',
    status: 'En revisión',
    due_date: '2026-07-15',
    is_overdue: false,
    title: 'Define solution hypotheses and quick wins',
    detail: 'First set of quick wins is drafted and waiting for validation.',
    dependency: 'Audit current flow and breakpoints',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-14-T04',
    project_code: 'PRJ-14',
    assignee_alias: 'Mateo Ruiz',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'Bloqueada',
    due_date: '2026-07-08',
    is_overdue: true,
    title: 'Get access to key data sources',
    detail: 'Blocked by permissions, repository access or owner confirmation.',
    dependency: 'Stakeholder mapping and scope',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-15-T01',
    project_code: 'PRJ-15',
    assignee_alias: 'Laura Gomez',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'En progreso',
    due_date: '2026-07-11',
    is_overdue: false,
    title: 'Stakeholder mapping and scope',
    detail: 'Interviews and dependency map are in progress.',
    dependency: null,
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-15-T02',
    project_code: 'PRJ-15',
    assignee_alias: 'Laura Gomez',
    assignee_role: 'Delivery',
    priority: 'Crítica',
    status: 'Por hacer',
    due_date: '2026-07-09',
    is_overdue: true,
    title: 'Audit current flow and breakpoints',
    detail: 'Current process timings, handoffs and failure points are still undocumented.',
    dependency: 'Stakeholder mapping and scope',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-15-T03',
    project_code: 'PRJ-15',
    assignee_alias: 'Laura Gomez',
    assignee_role: 'Delivery',
    priority: 'Media',
    status: 'En revisión',
    due_date: '2026-07-15',
    is_overdue: false,
    title: 'Define solution hypotheses and quick wins',
    detail: 'First set of quick wins is drafted and waiting for validation.',
    dependency: 'Audit current flow and breakpoints',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-15-T04',
    project_code: 'PRJ-15',
    assignee_alias: 'Laura Gomez',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'Bloqueada',
    due_date: '2026-07-08',
    is_overdue: true,
    title: 'Get access to key data sources',
    detail: 'Blocked by permissions, repository access or owner confirmation.',
    dependency: 'Stakeholder mapping and scope',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-16-T01',
    project_code: 'PRJ-16',
    assignee_alias: 'Mateo Ruiz',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'En progreso',
    due_date: '2026-07-11',
    is_overdue: false,
    title: 'Stakeholder mapping and scope',
    detail: 'Interviews and dependency map are in progress.',
    dependency: null,
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-16-T02',
    project_code: 'PRJ-16',
    assignee_alias: 'Mateo Ruiz',
    assignee_role: 'Delivery',
    priority: 'Crítica',
    status: 'Por hacer',
    due_date: '2026-07-09',
    is_overdue: true,
    title: 'Audit current flow and breakpoints',
    detail: 'Current process timings, handoffs and failure points are still undocumented.',
    dependency: 'Stakeholder mapping and scope',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-16-T03',
    project_code: 'PRJ-16',
    assignee_alias: 'Mateo Ruiz',
    assignee_role: 'Delivery',
    priority: 'Media',
    status: 'En revisión',
    due_date: '2026-07-15',
    is_overdue: false,
    title: 'Define solution hypotheses and quick wins',
    detail: 'First set of quick wins is drafted and waiting for validation.',
    dependency: 'Audit current flow and breakpoints',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-16-T04',
    project_code: 'PRJ-16',
    assignee_alias: 'Mateo Ruiz',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'Bloqueada',
    due_date: '2026-07-08',
    is_overdue: true,
    title: 'Get access to key data sources',
    detail: 'Blocked by permissions, repository access or owner confirmation.',
    dependency: 'Stakeholder mapping and scope',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-17-T01',
    project_code: 'PRJ-17',
    assignee_alias: 'Daniel Rojas',
    assignee_role: 'Commercial / Delivery',
    priority: 'Media',
    status: 'En progreso',
    due_date: '2026-08-14',
    is_overdue: false,
    title: 'Iteracion en curso con entregables definidos',
    detail: 'Scope acordado con el cliente, avance segun plan.',
    dependency: null,
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-17-T02',
    project_code: 'PRJ-17',
    assignee_alias: 'Daniel Rojas',
    assignee_role: 'Commercial / Delivery',
    priority: 'Alta',
    status: 'Por hacer',
    due_date: '2026-08-20',
    is_overdue: false,
    title: 'Validacion funcional del modulo',
    detail: 'Pendiente de arrancar cuando cierre la iteracion actual.',
    dependency: 'Iteracion en curso con entregables definidos',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-17-T03',
    project_code: 'PRJ-17',
    assignee_alias: 'Daniel Rojas',
    assignee_role: 'Commercial / Delivery',
    priority: 'Baja',
    status: 'En revisión',
    due_date: '2026-08-25',
    is_overdue: false,
    title: 'Documentacion para operacion del cliente',
    detail: 'Borrador listo, esperando revision del owner.',
    dependency: 'Iteracion en curso con entregables definidos',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-18-T01',
    project_code: 'PRJ-18',
    assignee_alias: 'Mateo Ruiz',
    assignee_role: 'Delivery',
    priority: 'Media',
    status: 'En progreso',
    due_date: '2026-08-14',
    is_overdue: false,
    title: 'Iteracion en curso con entregables definidos',
    detail: 'Scope acordado con el cliente, avance segun plan.',
    dependency: null,
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-18-T02',
    project_code: 'PRJ-18',
    assignee_alias: 'Mateo Ruiz',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'Por hacer',
    due_date: '2026-08-20',
    is_overdue: false,
    title: 'Validacion funcional del modulo',
    detail: 'Pendiente de arrancar cuando cierre la iteracion actual.',
    dependency: 'Iteracion en curso con entregables definidos',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-18-T03',
    project_code: 'PRJ-18',
    assignee_alias: 'Mateo Ruiz',
    assignee_role: 'Delivery',
    priority: 'Baja',
    status: 'En revisión',
    due_date: '2026-08-25',
    is_overdue: false,
    title: 'Documentacion para operacion del cliente',
    detail: 'Borrador listo, esperando revision del owner.',
    dependency: 'Iteracion en curso con entregables definidos',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-18-T04',
    project_code: 'PRJ-18',
    assignee_alias: 'Mateo Ruiz',
    assignee_role: 'Delivery',
    priority: 'Media',
    status: 'Por hacer',
    due_date: '2026-09-02',
    is_overdue: false,
    title: 'Cierre de fase y handoff',
    detail: 'Depende del cierre de la validacion funcional.',
    dependency: 'Validacion funcional del modulo',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-19-T01',
    project_code: 'PRJ-19',
    assignee_alias: 'Andrea Molina',
    assignee_role: 'Delivery',
    priority: 'Media',
    status: 'En progreso',
    due_date: '2026-08-14',
    is_overdue: false,
    title: 'Iteracion en curso con entregables definidos',
    detail: 'Scope acordado con el cliente, avance segun plan.',
    dependency: null,
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-19-T02',
    project_code: 'PRJ-19',
    assignee_alias: 'Andrea Molina',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'Por hacer',
    due_date: '2026-08-20',
    is_overdue: false,
    title: 'Validacion funcional del modulo',
    detail: 'Pendiente de arrancar cuando cierre la iteracion actual.',
    dependency: 'Iteracion en curso con entregables definidos',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-19-T03',
    project_code: 'PRJ-19',
    assignee_alias: 'Andrea Molina',
    assignee_role: 'Delivery',
    priority: 'Baja',
    status: 'En revisión',
    due_date: '2026-08-25',
    is_overdue: false,
    title: 'Documentacion para operacion del cliente',
    detail: 'Borrador listo, esperando revision del owner.',
    dependency: 'Iteracion en curso con entregables definidos',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-19-T04',
    project_code: 'PRJ-19',
    assignee_alias: 'Andrea Molina',
    assignee_role: 'Delivery',
    priority: 'Media',
    status: 'Por hacer',
    due_date: '2026-09-02',
    is_overdue: false,
    title: 'Cierre de fase y handoff',
    detail: 'Depende del cierre de la validacion funcional.',
    dependency: 'Validacion funcional del modulo',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-20-T01',
    project_code: 'PRJ-20',
    assignee_alias: 'Laura Gomez',
    assignee_role: 'Delivery',
    priority: 'Media',
    status: 'En progreso',
    due_date: '2026-08-14',
    is_overdue: false,
    title: 'Iteracion en curso con entregables definidos',
    detail: 'Scope acordado con el cliente, avance segun plan.',
    dependency: null,
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-20-T02',
    project_code: 'PRJ-20',
    assignee_alias: 'Laura Gomez',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'Por hacer',
    due_date: '2026-08-20',
    is_overdue: false,
    title: 'Validacion funcional del modulo',
    detail: 'Pendiente de arrancar cuando cierre la iteracion actual.',
    dependency: 'Iteracion en curso con entregables definidos',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-20-T03',
    project_code: 'PRJ-20',
    assignee_alias: 'Laura Gomez',
    assignee_role: 'Delivery',
    priority: 'Baja',
    status: 'En revisión',
    due_date: '2026-08-25',
    is_overdue: false,
    title: 'Documentacion para operacion del cliente',
    detail: 'Borrador listo, esperando revision del owner.',
    dependency: 'Iteracion en curso con entregables definidos',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-22-T01',
    project_code: 'PRJ-22',
    assignee_alias: 'Camila Torres',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'En progreso',
    due_date: '2026-07-12',
    is_overdue: true,
    title: 'Plan next delivery iteration',
    detail: 'Next iteration is being scoped with deliverables and owners.',
    dependency: null,
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-22-T02',
    project_code: 'PRJ-22',
    assignee_alias: 'Camila Torres',
    assignee_role: 'Delivery',
    priority: 'Crítica',
    status: 'Por hacer',
    due_date: '2026-07-10',
    is_overdue: true,
    title: 'Resolve priority issue in pilot or production',
    detail: 'There is a user-visible issue affecting trust or adoption.',
    dependency: 'Functional validation and release checklist',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-22-T03',
    project_code: 'PRJ-22',
    assignee_alias: 'Camila Torres',
    assignee_role: 'Delivery',
    priority: 'Media',
    status: 'Bloqueada',
    due_date: '2026-07-14',
    is_overdue: false,
    title: 'Align external dependency with client or vendor',
    detail: 'Waiting on client response, credentials, external API or business definition.',
    dependency: 'Resolve priority issue in pilot or production',
    depends_on_task_code: null,
  },
  {
    task_code: 'PRJ-22-T04',
    project_code: 'PRJ-22',
    assignee_alias: 'Camila Torres',
    assignee_role: 'Delivery',
    priority: 'Alta',
    status: 'En revisión',
    due_date: '2026-07-16',
    is_overdue: false,
    title: 'Functional validation and release checklist',
    detail: 'Core build exists, but edge cases still need validation before closing the front.',
    dependency: 'Plan next delivery iteration',
    depends_on_task_code: null,
  },
];

/**
 * Una dependencia que no se pudo resolver contra ninguna tarea (Tarea 2.2.c).
 * No se adivina una coincidencia parcial: se deja anotada para revisión manual.
 */
export type DependenciaPendiente = {
  task_code: string;
  project_code: string;
  dependency: string;
  motivo: 'sin coincidencia' | 'coincidencia ambigua' | 'se apunta a sí misma';
};

/**
 * Tarea 2.2 — traduce el texto libre de `dependency` al `task_code` real.
 *
 * La regla es: dentro del **mismo proyecto**, una tarea cuyo `title` sea igual
 * al texto de `dependency`. La comparación es exacta, no por prefijo ni por
 * parecido, y funciona porque el `title` ya viene sin el sufijo
 * ' - {project_name}' desde la Tarea 2.1.g. Con el título completo del Excel
 * esta regla resolvía 0 de 61 (ver `APRENDIZAJES.md` #7).
 *
 * Todo lo que no sea una coincidencia única sale por `pendientes` en vez de
 * resolverse a la fuerza: una dependencia mal apuntada nace como una tarea
 * 'Bloqueada' equivocada en el Kanban (regla de la Tarea 4.3.b).
 */
export function resolverDependencias(tareas: SeedTask[]): {
  resueltas: SeedTask[];
  pendientes: DependenciaPendiente[];
} {
  const pendientes: DependenciaPendiente[] = [];

  const resueltas = tareas.map((tarea) => {
    if (tarea.dependency === null) return tarea;

    const candidatas = tareas.filter(
      (otra) => otra.project_code === tarea.project_code && otra.title === tarea.dependency,
    );

    // 2.2.d — una tarea no puede depender de sí misma.
    const propia = candidatas.some((otra) => otra.task_code === tarea.task_code);
    const ajenas = candidatas.filter((otra) => otra.task_code !== tarea.task_code);

    if (ajenas.length === 1) {
      return { ...tarea, depends_on_task_code: ajenas[0].task_code };
    }

    const motivo: DependenciaPendiente['motivo'] =
      ajenas.length > 1 ? 'coincidencia ambigua' : propia ? 'se apunta a sí misma' : 'sin coincidencia';

    pendientes.push({
      task_code: tarea.task_code,
      project_code: tarea.project_code,
      dependency: tarea.dependency,
      motivo,
    });
    return tarea;
  });

  return { resueltas, pendientes };
}

const resolucion = resolverDependencias(tareasBase);

/** Las 82 tareas listas para insertar, con `depends_on_task_code` ya resuelto. */
export const seedTasks: SeedTask[] = resolucion.resueltas;

/**
 * 2.2.c — dependencias que quedaron sin resolver. Hoy está vacío (61 de 61
 * resueltas); si alguna vez trae filas, hay que revisarlas antes de correr el
 * seed de la Tarea 4.1, no ignorarlas.
 */
export const dependenciasPendientes: DependenciaPendiente[] = resolucion.pendientes;
